name: post-succeeded-deployment-workflow
run-name: 🚀 ${{ github.actor }} runs a post succeeded deployment workflow
on:
  # Run this workflow after a succeeded build & deploy
  workflow_run:
    workflows: ["pages-build-deployment"]
    # branches: [main]
    types: 
      - completed
jobs:
  request-google-search-indexing-for-changed-posts:
    runs-on: ubuntu-latest
    # 😊 Run this job only if the triggering workflow succeeded (and not just completed)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
        # 📖 https://github.com/marketplace/actions/changed-files
      - name: Get all post files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v41
        with:
          files_yaml: |
            post:               # ➡`post` key⬅
              - _posts/**.md

      - name: Setup Python
        if: steps.changed-files-yaml.outputs.post_any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Request Google Search re-indexing of the changed posts
        # ⚠ NOTE: Ensure all outputs are prefixed by the same key used above (➡`post` key⬅) e.g. `post_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.post_any_changed == 'true'
        env:
          ALL_CHANGED_POST_FILES: ${{ steps.changed-files-yaml.outputs.post_all_changed_files }}
          BLOG_BASE_URL: ${{ vars.BLOG_BASE_URL }}
          GOOGLE_SEARCH_INDEXING_API_KEYFILE: ${{ secrets.GOOGLE_SEARCH_INDEXING_API_KEYFILE }}
        run: |
          echo -e "List of all the post files that have changed:\n$ALL_CHANGED_POST_FILES\n"
          pip install oauth2client==4.1.3
          python ./.github/workflows/scripts/posts-google-search.py
